import Link from "next/link";
import { Header, Footer, Arrow, Spark, Shield, Search, AgentOrbit } from "./ui";

const cards = [
  ["01", "Interrogate the narrative", "A skeptical investor agent pressure-tests every claim, metric, and assumption in your deck.", <Shield key="s"/>],
  ["02", "Map the market", "Research agents surface competitors, positioning gaps, and the hard questions nobody wants to ask.", <Search key="s"/>],
  ["03", "Fix what matters", "Get a prioritized briefing that turns red flags into a sharper fundraising story.", <Spark key="s"/>]
];
export default function Home(){return <main><Header/><section className="hero grid-bg"><div className="eyebrow"><span/>MULTI-AGENT PITCH INTELLIGENCE</div><h1>Review your pitch<br/>before investors <i>do.</i></h1><p className="lede">VCynic reviews your narrative, maps relevant competitors, and organizes the questions your deck should answer.</p><div className="hero-actions"><Link className="button primary" href="/signup">Open the pitch workspace <Arrow/></Link><Link className="text-link" href="/how-it-works">How the review works <Arrow/></Link></div><AgentOrbit/></section><section className="section intro"><div><div className="eyebrow">WHAT THE REVIEW COVERS</div><h2>A more prepared<br/><i>next conversation.</i></h2></div><p>Bring your deck into one focused review. VCynic separates narrative questions, market context, and areas that need clearer evidence.</p></section><section className="features">{cards.map(([n,t,d,icon])=><article className="feature" key={t as string}><div className="feature-top"><small>{n}</small>{icon}</div><h3>{t}</h3><p>{d}</p><Link href="/how-it-works" aria-label={`Learn about ${t}`}><Arrow/></Link></article>)}</section><section className="cta-section"><div className="eyebrow">READY WHEN YOU ARE</div><h2>Start with a<br/>clearer pitch.</h2><Link className="button light" href="/signup">Open the workspace <Arrow/></Link><p>Review the privacy policy before submitting material.</p></section><Footer/></main>}
