"use client";
import Link from "next/link";
import { useState } from "react";
export const Arrow=()=> <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M3 10h13M11 4l6 6-6 6" fill="none" stroke="currentColor" strokeWidth="1.6"/></svg>;
export const Spark=()=> <svg viewBox="0 0 24 24"><path d="m12 2 1.8 7.2L21 11l-7.2 1.8L12 20l-1.8-7.2L3 11l7.2-1.8L12 2Z" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>;
export const Shield=()=> <svg viewBox="0 0 24 24"><path d="M12 3 20 6v5c0 5-3.4 8.4-8 10-4.6-1.6-8-5-8-10V6l8-3Z" fill="none" stroke="currentColor" strokeWidth="1.5"/><path d="m8.5 12 2.3 2.2 4.7-4.7" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>;
export const Search=()=> <svg viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="5.5" fill="none" stroke="currentColor" strokeWidth="1.5"/><path d="m15 15 5 5" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>;
export function Header(){const [open,setOpen]=useState(false);return <header><Link href="/" className="brand"><span className="brand-mark">V</span>VCYNIC</Link><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">Menu</button><nav className={open?"open":""}><Link href="/how-it-works">How it works</Link><Link href="/pricing">Pricing</Link><Link href="/contact">Contact</Link><Link href="/login">Log in</Link><Link href="/signup" className="nav-cta">Start free <Arrow/></Link></nav></header>}
export function Footer(){return <footer><Link href="/" className="brand"><span className="brand-mark">V</span>VCYNIC</Link><p>Pitch intelligence for founders<br/>preparing for investor conversations.</p><div><Link href="/how-it-works">How it works</Link><Link href="/pricing">Pricing</Link><Link href="/contact">Contact</Link><Link href="/login">Log in</Link></div><small>© 2026 VCynic. <Link href="/privacy">Privacy</Link> <Link href="/terms">Terms</Link> <Link href="/cookies">Cookies</Link> <Link href="/refunds">Refunds</Link></small></footer>}
export function AgentOrbit(){return <div className="orbit-wrap" aria-label="Animated visualization of AI agents analyzing a pitch deck"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="agent a1">Market<br/>Scout</div><div className="agent a2">Skeptic<br/>Agent</div><div className="agent a3">Signal<br/>Finder</div><div className="deck"><div className="deck-bar"/><strong>YOUR DECK</strong><span>12 slides analyzed</span><div className="deck-lines"><i/><i/><i/></div></div><div className="scanline"/></div>}
